version: '3'

# builds the api container and sets up the localstack container to run

services:
  api:
    build: .
    image: vanister/contacts_api
    depends_on:
      - localstack
    ports:
      - '3000:3000'
    container_name: contacts_api

    # these are the environment variables that are used in the api
    environment:
      AWS_ENDPOINT: 'http://dynamodb_localstack:8000' # localstack container host for dynamodb
      AWS_REGION: 'ap-southeast-1'
      AWS_ACCESS_KEY_ID: 'fake-access-key-id'
      AWS_SECRET_ACCESS_KEY: 'fake-access-key-id'

  localstack:
    image: localstack/localstack:latest
    ports:

      - '4566:4566' # new dynamodb port
      - '8080:8080' # the localstack admin portal
    container_name: dynamodb_localstack
    environment:
      SERVICES: dynamodb:8000
      DATA_DIR: '/tmp/localstack/data'
